#!/bin/bash

# createserver [name] [image] [user]

echo $@

declare -i dt
declare -i expires
dt=$(date +%s)
(( expires=dt+(1000*60*60*24*30) ))
./runredis hset srv:$1 status paid
./runredis hset srv:$1 expires $expires
./runredis lpush acct:$1 paid $amt date $dt for $1
tugboat create $1 -i 10581649 -k 711445
sleep 80
ip=$(tugboat info $1 | grep IP | tr -s ' ' | cut -d ' ' -f 2)
cd dns
./addorupdzone $1.oic.io $ip
cd ..
echo docker run -p 80:80 -d --name $1 $2/$3 | tugboat ssh $1
./runredis hset srv:$1 user $4
./runredis hset srv:$1 image $2/$3
./runredis hset srv:$1 name $1 
